# Site settings
title: Ferienwohnung "Unter Eichen" in Lingen
email: kontakt@fewo-unter-eichen.de
description: > # this means to ignore newlines until "baseurl:"
  Gelegen in einer ruhigen Wohnsiedlung, knapp 2 km vom Stadtzentrum Lingen entfernt, befindet sich in einem seperaten
  Anbau einer restaurierten Hofstelle mit altem Baumbestand und großzügiger Gartenanlage die Ferienwohnung
  "Unter Eichen"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fewo-unter-eichen.de" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude: [".gitignore", ".ruby-version", "Gemfile", "Gemfile.lock"]

sass:
  sass_dir: _sass

gems:
  - jekyll-sitemap
